#!/usr/bin/env bash

#[*] Name of the script: GoLang
#[*] Description: "Language Translator"
#[*] Version: 1.0
#[*] Author: JRIC2002
#[*] Date of creation: 03/05/2019
#[*] Date of last update: 30/04/2020

#COLORS
black='\033[1;30m'
red='\033[1;31m'
green='\033[1;32m'
yellow='\033[1;33m'
blue='\033[1;34m'
magenta='\033[1;35m'
cyan='\033[1;36m'
white='\033[0m'

#BANNER

function banner {
	
	printf "
	     $red ____       $yellow _
	     $red/ ___| ___  $yellow| |    __ _ _ __   __ _
	    $red| |  _ / _ \ $yellow| |   / _' | '_ \ / _' |
	    $red| |_| | (_) |$yellow| |__| (_| | | | | (_| |
	     $red\____|\___/ $yellow|_____\__,_|_| |_|\__, |$white v1.0
	                                   $yellow|___/

	   $green.:.:.$blue Script encoded by:$white @JRIC2002 $green.:.:.$white
         $green.:.:.$blue Description:$white Language Translator  $green.:.:.$white
	"

}

#TRADUCTOR

function traductor {
	
	echo ""
	printf "$green[$white\e001$green]$white Español => English\n"
	printf "$green[$white\e002$green]$white English => Español\n"
	printf "$green[$white\e099$green]$white Exit\n"
	echo ""
	
	printf "$green[$white*$green]$yellow Choose an Option:$white"
	read -p " " opcion

	if [ $opcion = "1" -o $opcion = "01" ]; then
		clear
		banner
		echo ""
		printf "$cyan Texto:$white"
		read -p " " texto
		echo ""
		printf "$green[$white*$green]$black Traduciendo Texto al Idioma Ingles...\n$white"
		sleep 3
		echo ""
		trans :en "$texto"
		echo ""
		printf "Presiona$yellow ENTER$white para volver..."
		read -p "" 
		
		clear
		banner
		traductor

	elif [ $opcion = "2" -o $opcion = "02" ]; then
		clear
		banner
		echo ""
		printf "$cyan Texto:$white"
		read -p " " texto
		echo ""
		printf "$green[$white*$green]$black Traduciendo Texto al Idioma Español...\n$white"
		sleep 3
		echo ""
		trans :es "$texto"
		echo ""
		printf "Presiona$yellow ENTER$white para volver..."
		read -p ""

		clear 
		banner
		traductor

	elif [ $opcion = "99" -o $opcion = "exit" ]; then
		echo ""
		printf "$red				¡Bye!\n$white"
		echo ""
	
	else 
		clear
		banner
		traductor
	fi

}

#FUNCIONES

banner
traductor

